CREATE DATABASE gov;

USE gov;

CREATE TABLE usuario(
    USU_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    /* TO DO VERIFIVAR VALIDOR DE CPF*/
    USU_CPF VARCHAR(30) NOT NULL,
    USU_SENHA VARCHAR(50) NOT NULL
);